version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run debug release
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: app/build/outputs/apk
          paths:
            - debug

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: /home/circleci/code/app/build/outputs/apk
      - run:
          name: Rename debug apk
          command: mv /home/circleci/code/app/build/outputs/apk/debug/app-debug.apk /home/circleci/code/app/build/outputs/apk/debug/$CIRCLE_TAG.apk
      - run:
          name: Install AWS cli
          command: sudo pip install awscli
      - run:
          name: Deploy to amazonS3
          command: aws s3 cp /home/circleci/code/app/build/outputs/apk/debug/$CIRCLE_TAG.apk s3://circleci-deneme/zero/

general:
  branches:
    only:
      - master
      - develop

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*.\w+/ # regex for v1.2.3 or v1.2.3-postfix
#      - test:
#          requires:
#            - build
#          filters:
#            tags:
#              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*.\w+/
            branches:
              ignore: /.*/
