version: 2

defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/android:api-26-alpha

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    machine: true
    environment:
      JVM_OPTS: -Xmx3200m
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run debug release
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  deploy:
    machine: true
    working_directory: ~/code
    <<: *defaults
    steps:
      - run:
          name: Get ghr tool
          command: go get github.com/tcnksm/ghr
      - run:
          name: Upload apk to Github
          command: curl --data '{"tag_name": $CIRCLE_TAG, "body": "Release of version 1.0.0","draft": false,"prerelease": false}' https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases?access_token=$GITHUB_TOKEN

general:
  branches:
    only:
      - master
      - develop

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/ # regex for v1.2.3
#      - test:
#          requires:
#            - build
#          filters:
#            tags:
#              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
