version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
        name: Chmod permissions
        command: sudo chmod +x ./gradlew
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
      - save_cache:
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
        name: Run Tests
        command: ./gradlew lint test
      - run:
        name: Run debug release
        command: ./gradlew assembleDebug
      - store_artifacts:
        path: app/build/outputs/apk
        destination: apk
      - store_artifacts:
        path: app/build/reports
        destination: reports
      - store_test_results:
        path: app/build/test-results

  release:
    docker:
      - image: circleci/node:latest
    working_directory: ~/code
    steps:
      - attach_workspace:
        at: ~/code
      - run: go get github.com/aktau/github-release
      - run:
        name: Upload apk to Github
        command: github-release upload --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --tag $CIRCLE_TAG --name $CIRCLE_PROJECT_REPONAME"."$CIRCLE_TAG"-build-"$CIRCLE_BUILD_NUM"" --file $CIRCLE_ARTIFACTS/$PROJECT_NAME-$CIRCLE_TAG

general:
  artifacts:
      - app/build/outputs/apk/
  branches:
    only:
      - master
      - develop

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/ # regex for v1.2.3
#      - test:
#          requires:
#            - build
#          filters:
#            tags:
#              only: /v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
